---
title: "Project_analysis"
author: "Aarav Gosalia 42576439"
date: "2025-03-04"
output: html_document
---

```{r}
library(readr)
library(ggplot2)
library(GGally)
library(tidyverse)

csv_file <- "reddit_engagement_data.csv"
df <- read_csv(csv_file, show_col_types = FALSE)

df_cleaned <- df %>% drop_na()
write_csv(df_cleaned, "reddit_cleaned.csv")

glimpse(df_cleaned)
```
```{r}
#summary(df_cleaned)
ggplot(df, aes(x = `Comment Score`)) +
  geom_histogram(fill = "blue", bins = 50, alpha = 0.7) +
  theme_minimal() +
  labs(title = "Distribution of Comment Scores",
       x = "Comment Score",
       y = "Frequency") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
df_filtered <- df_cleaned %>% filter(`Comment Score` >= -10 & `Comment Score` <= 50)
dim(df_filtered)

ggplot(df_filtered, aes(x = `Comment Score`)) +
  geom_histogram(fill = "blue", bins = 50, alpha = 0.7) +
  theme_minimal() +
  labs(title = "Zoomed-In Distribution of Comment Scores",
       x = "Comment Score",
       y = "Frequency") +
  theme(plot.title = element_text(hjust = 0.5))
                             
```

```{r}
subreddit_counts <- df_cleaned %>%
  group_by(`Subreddit Name`) %>%
  summarise(Comment_Count = n()) %>%
  arrange(desc(Comment_Count))

print(subreddit_counts)
```
```{r}
selected_cols <- c("Comment Score", "Number of Replies", "Sentiment Score", "Text Length", "User Karma")
df_subset <- df_cleaned %>% select(all_of(selected_cols))
pairs(df_subset, main = "Pair Plot of Selected Features")
```

